language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - pypy
after_success: 
install: pip install tox-travis
script: tox
cache:
  pip: true
notifications:
  webhooks:
    secure: CS6Bn+tOQnmMmeJ3DqVNF7T+J95Agx1BZoj1Ei+xYot5ABylmdTYdDykI7Foh/R9h0uQ7mWAocAUlMPlLUK+GNLH121rA7CmcrTT8jNHmTvFkKgBFRYNvwWqE/xYru1XaSwkMjaqqkTvoLwTpSHmVqUp3AqVYf+/GLYp5pCqX+cn4vPojGom0pehbOCw+zN19x3SP5ay2J4dqPZEjV/KKsi0h1m/l+vRVMOGZqS24DpyeyfkNR7TEwCe43J/x32RjvwfUdpuGdYJo6xlQpJKq6bmVTyscsVhSiSqrcvvqlSlcKm4ftVbgKNzAcuc5lPtL84PwDt1wEVhJ8+ZmSy9KdBs87NOAd61XjgfRKzJ2z4qOw8T2KJBkFJUb9JiYXl5pEVURjrt4WbsXik5zQV36Lo52KSPfyeuYq4JQHiLN0aV9RxmwcAtietBIX5gm/CBpYICIFNgCrAodmKVj9P59/nc8G+zEHhCENWnfZJWmXU4gpWq7QjIRenZh5yFNhJi3MiKxTi7Hmt9qgbRN5x6134EbAtZJi78pZOzFd9+8gJCTqN+XXlZFdVvRjqUGNlil0/tbThLp9+rbI+OAQXHmi/yezbd6/egZzuXts0NcAqLmlSV5KYeN63FDxjE5EJfB1qAPGpOECyXWy3D1De5Wed6rirSV++2bnWfLIf0AeY=
